services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.nathanfourny.com`)"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=myresolver"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true